services:
  postgres:
    image: postgres:18
    container_name: myPostrges2
    environment:
      POSTGRES_DB: aston_hw2
      POSTGRES_USER: aston_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  config-server:
    build:
      context: ./my-config-server
      dockerfile: Dockerfile
    container_name: config-server-container
    ports:
      - "8888:8888"
    restart: on-failure:3

  service-discovery:
    build:
      context: ./my-service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery-container
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    restart: on-failure:3
    environment:
      CONFIG_SERVER_HOST: config-server

  circuit-breaker:
    build:
      context: ./my-circuit-breaker
      dockerfile: Dockerfile
    container_name: circuit-breaker-container
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - service-discovery
      - user-service
    restart: on-failure:3
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: service-discovery

  gateway:
    build:
      context: ./my-gateway
      dockerfile: Dockerfile
    container_name: gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - service-discovery
      - user-service
    restart: on-failure:3
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: service-discovery

  user-service:
    build:
      context: ./PostgresCRUD2
      dockerfile: Dockerfile
    container_name: user-service-container
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - postgres
      - service-discovery
    restart: on-failure:3
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: service-discovery
      POSTGRES_HOST: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_KAFKA_ENABLED: true

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service-container
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - service-discovery
    restart: on-failure:3
    environment:
      CONFIG_SERVER_HOST: config-server
      EUREKA_HOST: service-discovery
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.5
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1