server:
  port: 8082

app:
  kafka:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false
    hostname: ${HOSTNAME:localhost}

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/aston_hw2
    username: aston_user
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 2
        failureRateThreshold: 100
        minimum-number-of-calls: 2
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - com.aston.homework.service.UserServiceException